# Generated by Django 2.1.2 on 2018-10-31 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='haitem',
            options={'verbose_name': 'Hausaufgaben Eintrag', 'verbose_name_plural': 'Hausaufgaben Einträge'},
        ),
        migrations.RenameField(
            model_name='haitem',
            old_name='exercise',
            new_name='Aufgabe',
        ),
        migrations.RenameField(
            model_name='haitem',
            old_name='author',
            new_name='Autor',
        ),
        migrations.RenameField(
            model_name='haitem',
            old_name='date_until',
            new_name='Bis',
        ),
        migrations.RenameField(
            model_name='haitem',
            old_name='subject',
            new_name='Fach',
        ),
        migrations.RenameField(
            model_name='haitem',
            old_name='info',
            new_name='Infos',
        ),
        migrations.RenameField(
            model_name='haitem',
            old_name='date_created_at',
            new_name='Von',
        ),
    ]
