# Generated by Django 2.1.2 on 2018-10-31 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ha', '0002_auto_20181031_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='haitem',
            old_name='Autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='haitem',
            old_name='Von',
            new_name='date_created_at',
        ),
        migrations.RenameField(
            model_name='haitem',
            old_name='Bis',
            new_name='date_until',
        ),
        migrations.RenameField(
            model_name='haitem',
            old_name='Aufgabe',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='haitem',
            old_name='Infos',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='haitem',
            old_name='Fach',
            new_name='subject',
        ),
    ]
